version: '3'
services:
  postgres-db:
      image: postgres
      container_name: postgres-db
      environment:
        POSTGRES_USER: "${DB_USER}"
        POSTGRES_DB: "${DB_NAME}"
        POSTGRES_PASSWORD: "${DB_PASSWORD}"
      ports:
        - ${DB_PORT}:5432
      volumes:
        - ../dkdata/postgres:/var/lib/postgresql/data
      restart: always

  nginx:
    image: nginx
    container_name: nginx
    network_mode: "host"
    volumes:
      - ./nginx/default_local:/etc/nginx/conf.d/default.conf

  metabase:
    image: metabase/metabase
    container_name: metabase
    hostname: metabase
    volumes:
      - ../dkdata/metabase:/dev/random
    ports:
      - 3002:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: "${DB_NAME}"
      MB_DB_USER: "${DB_USER}"
      MB_DB_PASS: "${DB_PASSWORD}"
      MB_DB_HOST: postgres-db
      MB_DB_PORT: "${DB_PORT}"
    depends_on:
      - postgres-db
    restart: always
